# Etapa 1: Build
FROM node:18-alpine AS builder

WORKDIR /app

# Copiamos los archivos necesarios
COPY package*.json ./
RUN npm install

COPY tsconfig.json ./
COPY src ./src

# Compilar TypeScript a JavaScript
RUN npm run build

# Etapa 2: Producción
FROM node:18-alpine

WORKDIR /app

# Copiar solo el código compilado y node_modules
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY package*.json ./

# Exponer el puerto si es necesario
EXPOSE 3002

# Comando para correr la app
CMD ["node", "dist/main.js"]
