version: '3.8'

services:
  api:
    build: .
    container_name: product-api-js
    ports:
      - "3010:3010"
    env_file: .env
    volumes:
      - .:/app
    depends_on:
      - rabbitmq

  worker:
    build: .
    container_name: product-worker-js
    command: npm run worker
    env_file: .env
    volumes:
      - .:/app
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
